### ISSUE TITLE
关于成就「情有独钟(五星角色)」

### ISSUE THREAD

**Issue by Aniverse** [voderl/genshin-gacha-analyzer#1]
当没有重复的五星角色时，不应该显示这个成就。

另外也可以增加成就统计重复的四星武器和五星武器？

**Comment by voderl** [comment]
角色的话确实可以，如果最多的数量为1就不显示情有独钟了。
武器的话，可能有点占成就位置，并且相对于角色关注度不高。同时武器个人感觉不是主观上想要获取某个武器才去抽的，更多是作为角色的副产物，也不太适配现有文案，如果有好的文案也可以考虑一下。
