### ISSUE TITLE
论 将角色与武器数量进统计展示的 可行性

### ISSUE THREAD

**Issue by ReStartLin** [voderl/genshin-gacha-analyzer#10]
赞这个项目, 大佬太强了

然后
因为数据的存在(虽然有官方的时间限制)
可以做到以下几点:
1.  推测角色池    然后将角色 -- > 数量 进行展示(显示命星更贴近玩家 23333)     如果不考虑网站资源的话, 可以直接用轮播的 大角色图来进行展示, 更为丰富
2.  同上,  玩家们是时候知道到底什么垃圾3星武器占据卡池了23333   统计那些废铁

3. 我觉得在第一栏 日期-抽卡次数 的统计中, 感觉字体可加大突出, 然后使用折线图会感觉友好一点.

再次,敬佩 23333

**Comment by voderl** [comment]
感谢反馈。
这些统计的展示用什么格式好呀，感觉表格适合一点，文字云也比较好，饼图就可能太杂了。
抽卡次数柱状图，其实有一个没什么存在感的功能 (点击展开当日数据) ，我可以测试一下折线图的展示效果。

**Comment by ReStartLin** [comment]
统计角色持有量的话我觉得可以这样
像助手一样总览:
![image](https://user-images.githubusercontent.com/31606497/111468163-37efba80-8760-11eb-8fb0-81888881c953.png)
然后. 每个角色能点开大图(动态就更好了): 类似于
 
![image](https://user-images.githubusercontent.com/31606497/111468230-4a69f400-8760-11eb-85a7-eafeb9d68503.png)


hhh  文字云 也挺有意思的  
然后我觉得 让玩家能知道什么垃圾武器出得最多 真的好有吐槽意义hhh

**Comment by ReStartLin** [comment]
可惜开源的前端不太适合做数据收集, 不然像作者你这个 五星平均出货的数据 一旦大量统计起来有效数据  还挺有意义的(骗氪或者劝退hhh)

**Comment by voderl** [comment]
加图片展示还是有点犹豫的。打算先搞个文字云类似的东西，之后找到图片源后再考虑加图片( 文字云加个图像图标感觉也蛮有意思的

**Comment by ReStartLin** [comment]
2333 确实

**Comment by voderl** [comment]
先加了文字云，在分析图那一栏，有点丑 ( 捂脸

**Comment by ReStartLin** [comment]
> 先加了文字云，在分析图那一栏，有点丑 ( 捂脸

2333 看到了  只是有点觉得词条云有点卑微 没有槽点放在下面hhh  然后整体不居中有点怪异
2333 最好加上吐槽描述, 例如毒瘤出货武器什么的   然后词条云生成png好弄么

**Comment by voderl** [comment]
吐槽描述感觉不太好写，也没几句写的，而且容易杀人诛心(×
生成图片应该挺好弄的，我尽快加上

**Comment by LaoshuBaby** [comment]
> 
> 
> 吐槽描述感觉不太好写，也没几句写的，而且容易杀人诛心(×
> 生成图片应该挺好弄的，我尽快加上

杀就杀，杀也是先杀策划（捂脸

**Comment by voderl** [comment]
近期将词云更新到了图片云. [Demo](https://genshin.voderl.cn/#=Nn76tHK~f4mENVDRCxCg6TXdXqdUc5sOOMtsENKCoQlio2YT6lUK2qJvH811r21Ja7GdCEGLUu52bkhPmJzKWbkLB6YI5rFzNWniO7xx7YpbuJRbjzcWpPJm31WtcVHbZOl8Xx7thl97KPgrlZuKDorp5GSVZ6jxDoSc6FyILedBa2fiNTlQmnyI5S~WSEk7a3xpZd8DrZvO889y08Qnk4HOkplTEGUYpCSUg428JfPKOWtzJV1ROKsnHp1VfISKErUpjm1qZH8QbkIurg7Fn7bMqkg7TEKP0KN9oS4yldQUeopH0lmDYvUwatZUr7W5yy~cNX3TIOc7VJdtNcNO~7OnIic6bxs0bjAteOUoiDrNju5YW4UD6q33UZZDm1TYsUZx8u=ZSmMysHKWf0kQZyG8eO~~nxJ6z1bC9VUaPSyNPKjF4bDGJ56pTWp9R=TJMUpPNZ=1xg6USkdhqXQiyf3WIT1LBHky56oHn2PhfKKEyCesKHlDJLyU=g7l8xwwkJ1DWRWa7Wilh0Mk2OklbRJ~niP6OaVuMkpq=JRYpCTDqkl1JFLi4A1D61NsXXkFG1RdCnGbVQFEkbtVCg=j6erOZNoSLoMtSIkqhJUqpKmW=2ti8xr2oyiObdSFtBjQmoNq26TquiknhDylHt2fqgv2=Zc2LalmNqrJWxGTFJPZ=zD89MttqXh5QJeC6pq6~RrqicxzIPWK3UjoqljVebfHecZjVY5kGqZi~bzcqhJPFdt9Ep3zYw2RvrMZeiG=dLDnFsCE:MaZ1Wmcr4mWuMTMduqS3iMrRLnrFjZuXMcxrTQ5u~4QhbN8Mu~Me~8epFlvWc4rRXDoB3CmYHj580517780xVL4hvcZZmncSlOELQmrQxPdc2IXa0rC1anoa662cW4jKl55ywhQze=ADM2oTJuFZVjBvorzUOctR0nad8CEOXTlpS1DcoJsnbW3CuIXalsxjPEo2vh1xhN88Y6dab918uM~es995nfrLTjTHju1zh4dlOUN43yRxinWkZblfTJXV4wgrrmvGe=eCT3yUqUhjdTLjjXHLnya2Z45q94p8lxvvrnvT106im2jOim64nfOuKfmXm2GeHfc533kWe2~3UxyffjHLimWveR8SoctBDMOVsWxo7nPLbpk~O8lsfN5G2MqQheGGJZ7nw53nzxxwywx56pz2PWJdnipdceVT4Fnnlxhltyfgr4c9Hb5o3eFKUyz5dmOZZhZ3Y~EqXhK8XVm9x1GNrymWnWfenm1q06zKMJ0s1SY3602LTDDDvab61080P51plcjGme2JaH6886md9u~NN99=LmOeM4WR9N=N~MMOLmWPG~eGWOVwubuB973O~O=eWO3V4nEaxtXR86XZUrE7jHNONd8nGEqK5y8hJ~Z88OdCnzPvzl1rULzPM~~uG3mhaY9Z5a0Os9vMtD5eV~vIizxmNbmaaozvSMBpWUly02nx27wyO3nLiteUpvutnGsdOC67O2vY1eW97zn3WLzO~GE3jnudzqLlbwzvfW0g05fMIa25EtcdtPOJc7qG5wvJPW20pR1SJGdNe9tMec7fE~fG~2=MTdVw3m2D4SfBtTdc3hF8Jb74Zba8y~GW2uGWWG5c7eHvgXPmuG9EF:1)
![wordcloud-demo](https://user-images.githubusercontent.com/43035138/194479348-7ac56eed-0541-46d2-b8dd-95a7352aa770.png)
