### ISSUE TITLE
关于筛选的实现

### ISSUE THREAD

**Issue by ktKongTong** [voderl/genshin-gacha-analyzer#11]
我自己用python也写了一个祈愿汇总的小工具数据处理用的是pandas，为了方便使用这个工具，现在想支持excel导出，数据类型应该都是对上了的，但是筛选四星，五星就筛选不了，所以想问问这个工具实现筛选的方式，我好在生成excel进行处理，难道是筛选颜色的方式吗?
![image](https://user-images.githubusercontent.com/44502608/112025448-20ee0580-8b70-11eb-948c-f9858b7362b5.png)

![image](https://user-images.githubusercontent.com/44502608/112025402-159ada00-8b70-11eb-82d8-191e54c700ed.png)

**Comment by voderl** [comment]
是只是单纯比对星级的，但可能因为某种格式原因，将星级解析成了字符串类型，没有转为数字？方便给一下文件嘛，只留一条数据就好，我确认一下。

**Comment by voderl** [comment]
先访问这个网址确认一下吧：
https://genshin-gacha-analyzer-git-dev-voderl.vercel.app/

**Comment by ktKongTong** [comment]
> 是只是单纯比对星级的，但可能因为某种格式原因，将星级解析成了字符串类型，没有转为数字？方便给一下文件嘛，只留一条数据就好，我确认一下。


哦哦，是我的问题，dataframe在解析的时候将rank_type字段解析成了str类型，转成int类型就好了，漏了这点😀

已经处理好了
![image](https://user-images.githubusercontent.com/44502608/112085597-c97a8480-8bc5-11eb-8305-05ea39953be4.png)
