### ISSUE TITLE
时间轴界面，无抽卡日展示错误

### ISSUE THREAD

**Issue by zhsitao** [voderl/genshin-gacha-analyzer#12]
如下图，在时间轴界面，当选中显示没有抽卡的日期时，会导致在左侧添加所有日期，但柱状图为空。
![image](https://user-images.githubusercontent.com/3782634/112642008-c0c8cd80-8ea7-11eb-96b4-6119e807958b.png)

我记得原来没有这个bug，应该是最近新引入的。

**Comment by voderl** [comment]
感谢反馈。是的，今天更新了一下这个图。但我的数据可以正常显示，我尝试定位一下

**Comment by zhsitao** [comment]
> 感谢反馈。是的，今天更新了一下这个图。但我的数据可以正常显示，我尝试定位一下

发现bug时我是用的这个帖子的数据：
https://ngabbs.com/read.php?tid=25280092

**Comment by voderl** [comment]
所以这就很迷惑了。同样的数据我这边正常显示，怀疑可能和浏览器有关，但我试了几个浏览器也试不出来。试试ctrl+f5刷新一下
![image](https://user-images.githubusercontent.com/43035138/112707691-19b85600-8ee8-11eb-952e-01b33f728b8b.png)

**Comment by zhsitao** [comment]
> 所以这就很迷惑了。同样的数据我这边正常显示，怀疑可能和浏览器有关，但我试了几个浏览器也试不出来。试试ctrl+f5刷新一下

刚刚发现我用上面的原数据也复现不了了。。。也许是当时我浏览器出问题了？

不过有个新bug，restore按钮点击后会变成空白，点左上角“显示没有抽卡的日期”切换才能正常显示：
![image](https://user-images.githubusercontent.com/3782634/112707782-bdb6f700-8f12-11eb-93d5-af7d4dde78b5.png)

**Comment by voderl** [comment]
是的，那几个按钮其实都没什么用(×，感觉只留一个下载就行了
