### ISSUE TITLE
成就「雨时偏比晴时多」有问题

### ISSUE THREAD

**Issue by nil-err** [voderl/genshin-gacha-analyzer#13]
我小保底应该只歪了一次，迪卢克
新手池抽出了一个莫娜，常驻一个琴

但是分析出该成就我歪了3次——3/3

「雨时偏比晴时多」
在「角色活动祈愿」中，小保底偏向于没有抽中当期Up角色
3 / 3
小保底歪的概率

**Comment by voderl** [comment]
感谢反馈。可以提供一下抽卡记录吗？我这边暂时复现不出来。也可以截个图看一下，原数据-角色活动祈愿-筛选(五星)

**Comment by nil-err** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/24436433/112918088-a8baad80-9136-11eb-8da0-ed9ae15d1089.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/24436433/112917956-57aab980-9136-11eb-8b17-cf88e98343cc.png">
这个，我刚刚还发现，选择某一个池子进行筛选的时候，是一个条目都没有的
<img width="848" alt="image" src="https://user-images.githubusercontent.com/24436433/112918054-99d3fb00-9136-11eb-9fa5-227605f3b068.png">

**Comment by nil-err** [comment]
浏览器为Safari 
版本14.0.3 (16610.4.3.1.7)

**Comment by nil-err** [comment]
刚刚使用Firefox测试了一下，是正常的，所以我之前的问题应该是Safari导致的。

感谢，已经能够正常使用了，当然如果Safari端能够修复就更好了

**Comment by voderl** [comment]
感谢。终于弄明白原因了，主要手边没safari端，所以不太方便测试，会尽快尝试修复的

**Comment by nil-err** [comment]
感谢，辛苦你了

**Comment by voderl** [comment]
太感谢了，我之前就见到别人导出的图片里的格式不太对，但没有太在意。
今天找出的原因是 safari 默认解析时间不能识别 "2020-09-28 10:25:28" 格式，导致和时间相关的都不对了。
问题应该解决了，也麻烦测试一下 (不排除引入了新的bug(×
再次感谢~

**Comment by nil-err** [comment]
说到时间，我刚刚去看了一下其他功能都正常了，但是时间轴的功能好像不太正常
打开 **_显示没有抽卡的日期_** 这个开关之后，出现时间轴的重叠、错位，具体如下面这张图(主要在这张图的右上角)
还有就是点击2020-01-31这一天的柱子，下面出现的抽卡记录同时出现了2020-02-03这一天的
修复bug辛苦了，感谢！
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/24436433/113013251-240b7600-91ae-11eb-89d6-7e55f6313bb3.png">

**Comment by voderl** [comment]
这个问题感觉有点玄学(× 我试了一下safari，没有出现这个问题
感觉也类似这个：https://github.com/voderl/genshin-gacha-analyzer/issues/12
能在哪个浏览器下稳定复现吗？

**Comment by nil-err** [comment]
我现在是可以在Firefox(macOS:11.2.3 (20D91) , Firefox: 86.0 (64 位)) 和 Safari (14.0.3 (16610.4.3.1.7))均可以复现，使用两个账号的数据都出现了这种情况
更新Firefox到(87.0 (64 位))版本之后，问题还是存在
使用的导出工具应该是https://ngabbs.com/read.php?tid=25559039

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/24436433/113016507-21f6e680-91b1-11eb-8123-a8424d6ab9b9.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/24436433/113016542-2d4a1200-91b1-11eb-9f64-d570a87e6747.png">

**Comment by voderl** [comment]
确实引入了新的bug，是我没有做好测试。简单因为在js里月份从0开始(×
然后因为大部分日期信息都有这个问题，达到了微妙的平衡，导致在大体上看不出错误 (捂脸

**Comment by nil-err** [comment]
应该已经好了，辛苦了
感谢！
