### ISSUE TITLE
希望时间轴能统计一段时间的总共抽卡数与角色数

### ISSUE THREAD

**Issue by NatralMicsear** [voderl/genshin-gacha-analyzer#14]
比如想单独统计某个月份的抽卡数和角色数、某个版本的抽卡数和角色数。但现有的时间轴貌似只能缩放到一段时间，不能显示该段时间的总计抽卡数和角色数。
或者，在分析图那里列出各个月、某个版本的抽卡分析？

**Comment by voderl** [comment]
感谢反馈，但是感觉这些不太好加，再加上操作逻辑就更一塌糊涂了。
目前在 原数据 - 筛选 里可以选择每个up池的抽卡数据 (虽然现在同名卡池的显示一团糟)

如果要加的话，可以先在 原数据 - 筛选 里加一个自定时间范围筛选，但最开始也是嫌操作麻烦而只留下了up池筛选，如果改成自定时间范围会有一点帮助吗？

**Comment by NatralMicsear** [comment]
> 感谢反馈，但是感觉这些不太好加，再加上操作逻辑就更一塌糊涂了。
> 目前在 原数据 - 筛选 里可以选择每个up池的抽卡数据 (虽然现在同名卡池的显示一团糟)
> 
> 如果要加的话，可以先在 原数据 - 筛选 里加一个自定时间范围筛选，但最开始也是嫌操作麻烦而只留下了up池筛选，如果改成自定时间范围会有一点帮助吗？

非常感谢作者回复，其实我本意是在时间轴界面选中一段时间后呈现成这样：
![图片1](https://user-images.githubusercontent.com/32427300/113426411-01739a00-9406-11eb-9039-e445a5bec493.png)

其实也只是一时的想法，我对编程了解甚少，如果实现起来不容易就当这个建议不存在好啦

**Comment by voderl** [comment]
看到示意图懂了，清晰明了，赞。我之前以为要加很多用户操作逻辑。
提需求当然没必要考虑实现难度，我尽量尝试去实现~

**Comment by voderl** [comment]
更新了一版。也麻烦看一下是否满足需求，有问题随时提出，谢谢~

**Comment by NatralMicsear** [comment]
> 更新了一版。也麻烦看一下是否满足需求，有问题随时提出，谢谢~

非常好，感谢作者
