### ISSUE TITLE
希望增加一个能合并两个Excel的功能

### ISSUE THREAD

**Issue by nil-err** [voderl/genshin-gacha-analyzer#15]
目前游戏已经6个多月了，官方给出的只记录6个月的抽卡记录
虽然可以手动合并之前导出和现在导出的抽卡记录，但还是略微有点麻烦，并且还容易出错
因此希望能够增加一个能上传两个Excel，然后导出为一个文件的功能，这样就能将抽卡一直记录下来

**Comment by voderl** [comment]
感谢反馈，一般的导出工具都能自动合并之前的记录。
不过手机端的部分导出工具没有这个功能，这个还是很有必要的，会尽快加上

**Comment by voderl** [comment]
目前加上了合并功能，不过页面变得更丑了(×。也麻烦测试一下能否正常使用，谢谢~

**Comment by nil-err** [comment]
感谢～
