### ISSUE TITLE
希望能支持登录米哈游通行证账户来获取抽卡记录，否则太麻烦了

### ISSUE THREAD

**Issue by AkarinLiu** [voderl/genshin-gacha-analyzer#17]

**Comment by voderl** [comment]
米哈游通行证账户是官方的，所以是无法支持的。
不过有一个项目是支持通过输入 离线链接 来获取抽卡记录的
项目github地址： https://github.com/ktKongTong/genshin-gacha-helper-mobile
网站：https://genshin-gacha-helper-mobile.vercel.app/
