### ISSUE TITLE
无法正常下载分析图

### ISSUE THREAD

**Issue by AkarinLiu** [voderl/genshin-gacha-analyzer#18]

**Comment by voderl** [comment]
感谢反馈，可以先尝试更换浏览器。
也麻烦留一下设备和浏览器。因为个人测试设备有限，非常抱歉，会尽快尝试修复。

**Comment by AkarinLiu** [comment]
![Screenshot_2021-04-25-16-18-53-946_com android settings](https://user-images.githubusercontent.com/58081491/115986320-3678a400-a5e2-11eb-9ebb-826eb81f3c6c.jpg)

**Comment by AkarinLiu** [comment]
![Screenshot_2021-04-25-16-21-29-903_com microsoft emmx](https://user-images.githubusercontent.com/58081491/115986349-54de9f80-a5e2-11eb-9755-a4eb18138d6d.jpg)

**Comment by AkarinLiu** [comment]
MIUI debug报告:https://cowtransfer.com/s/db9a29555e3640

**Comment by voderl** [comment]
使用同一版本Edge浏览器进行测试，可以正常保存下载图片。
不过在第一次下载时提示申请存储权限，可以检查一下浏览器是否开启存储权限。
也可以给出存储失败的截图或描述，便于进一步确认，谢谢。
