### ISSUE TITLE
成就图不清晰，成就字库太少

### ISSUE THREAD

**Issue by Rakau** [voderl/genshin-gacha-analyzer#19]
RT，成就图导出只有720P也太小了，能支持1080、2K、4K、8K就好了。另外字库不足用F12自己改的时候字体缺字

**Comment by voderl** [comment]
字库缺字是因为 会扫描工程所有文件，将使用到的中文字体生成压缩字体，减小字体包的大小。
成就图导出也不太方便选择清晰度，我可以把清晰度调高一点试试看
