### ISSUE TITLE
文件格式支持

### ISSUE THREAD

**Issue by Lightczx** [voderl/genshin-gacha-analyzer#22]
我[自己的工具](https://github.com/DGP-Studio/Snap.Genshin)导出的xlsx为下面的格式
![image.png](https://i.loli.net/2021/08/05/T1wCdatfr68MHZh.png)

但是好像这个工具不支持读取卡池id作为SheetName的工作簿
希望可以修改一下来兼容

**Comment by voderl** [comment]
感谢反馈，这个可以加上的。方便给个xlsx记录文件吗，我测试一下。直接这里上传，或者加QQ私发给我吧（*******）

**Comment by Lightczx** [comment]
涉及到了一点点隐私，我加qq发吧

**Comment by voderl** [comment]
已经添加了支持，也麻烦测试一下吧~

**Comment by Lightczx** [comment]
Great job！
