### ISSUE TITLE
支持 JSON 导入?

### ISSUE THREAD

**Issue by morlay** [voderl/genshin-gacha-analyzer#26]
还可以支持从 URL 中拿数据 `?import=base64([{}])`，以方便脚本抓取并跳转

结构可用和官方一致

```js
[{
  gacha_type: "301"
  id: "1629237960000159359"
  item_id: ""
  item_type: "武器"
  lang: "zh-cn"
  name: "以理服人"
  rank_type: "3"
  time: "2021-08-18 06:58:28"
}]
```

**Comment by voderl** [comment]
目前在做通过url导入导出数据。
不过是和脚本抓取跳转还是不一样的，是希望用户的抽卡数据可以通过url分享出去，因为数据可能有几千甚至上万个，所以需要追求比较好的压缩方法。目前实现了日期数据的压缩，大概891个日期数据，压缩后字符1100+，还在想办法做角色id的压缩

如果直接原数据结构的话，url抽卡数据太多的话可能会有限制

**Comment by morlay** [comment]
数据传递太麻烦，api 又有跨域限制，走页面脚本好了

https://github.com/morlay/genshin-gacha-analyzer 写了个简版 🤣 

![image](https://user-images.githubusercontent.com/1667873/130777965-29bbd286-f492-4cde-8613-c5837c29f5a1.png)

**Comment by voderl** [comment]
更新了个通过 url 导入和导出数据，可以试试看。[点击前往](https://genshin-gacha-analyzer.vercel.app/#=Nn76tHK~f4mENVDRCxCg6TXdXqdUc5sOOMtsENKCoQlio2YT6lUK2qJvH811r21Ja7GdCEGLUu52bkhPmJzKWbkLB6YI5rFzNWniO7xx7YpbuJRbjzcWpPJm31WtcVHbZOl8Xx7thl97KPgrlZuKDorp5GSVZ6jxDoSc6FyILedBa2fiNTlQmnyI5S~WSEk7a3xpZd8DrZvO889y08Qnk4HOkplTEGUYpCSUg428JfPKOWtzJV1ROKsnHp1VfISKErUpjm1qZH8QbkIurg7Fn7bMqkg7TEKP0KN9oS4yldQUeopH0lmDYvUwatZUr7W5yy~cNX3TIOc7VJdtNcNO~7OnIic6bxs0bjAteOUoiDrNju5YW4UD6q33UZZDm1TYsUZx8u=ZSmMysHKWf0kQZyG8eO~~nxJ6z1bC9VUaPSyNPKjF4bDGJ56pTWp9R=TJMUpPNZ=1xg6USkdhqXQiyf3WIT1LBHky56oHn2PhfKKEyCesKHlDJLyU=g7l8xwwkJ1DWRWa7Wilh0Mk2OklbRJ~niP6OaVuMkpq=JRYpCTDqkl1JFLi4A1D61NsXXkFG1RdCnGbVQFEkbtVCg=j6erOZNoSLoMtSIkqhJUqpKmW=2ti8xr2oyiObdSFtBjQmoNq26TquiknhDylHt2fqgv2=Zc2LalmNqrJWxGTFJPZ=zD89MttqXh5QJeC6pq6~RrqicxzIPWK3UjoqljVebfHecZjVY5kGqZi~bzcqhJPFdt9Ep3zYw2RvrMZeiG=dLDnFsD0FL=zpuvjfkoQj9opqCjmNY13xXZHjIl=3Xr8tt=THTqg5VWOs4DHryxqfIl89R9MsOnkPsQZ8vzfZmH0mb98M=LWv0l0sOq9VUHUf4DQmBck=xx9qDcdDDnlKt6TSer3aZMX~ekXuO302X61ac2kVskxjS1WsBzmMg~8x5tQ2P5S79ngDpmDRienlHXal6WdoMZTdQandVrGV6WLt~c=UuaFcZjjklwMiAnDGIr4:MaZ1Wmcr4mWuMTMduqS3iMrRLnrFjZuXMcxrTQ5u~4QhbN8Mu~Me~8epFlvWc4rRXDoB3CmYHj580517780xVL4hvcZZmncSlOELQmrQxPdc2IXa0rC1anoa662cW4jKl55ywhQze=ADM2oTJuFZVjBvorzUOctR0nad8CEOXTlpS1DcoJsnbW3CuIXalsxjPEo2vh1xhN88Y6dab918uM~es995nfrLTjTHju1zh4dlOUN43yRxinWkZblfTJXV4wgrrmvGe=eCT3yUqUhjdTLjjXHLnya2Z45q94p8lxvvrnvT106im2jOim64nfOuKfmXm2GeHfc533kWe2~3UxyffjHLimWveR8SoctBDMOVsWxo7nPLbpk~O8lsfN5G2MqQheGGJZ7nw53nzxxwywx56pz2PWJdnipdceVT4Fnnlxhltyfgr4c9Hb5o3eFKUyz5dmOZZhZ3Y~EqXhK8XVm9x1GNrymWnWfenm1q06zKMJ0s1SY3602LTDDDvab61080P51plcjGme2JaH6886md9u~NN99=LmOeM4WR9N=N~MMOLmWPG~eGWOVwubuB973O~O=eWO3V4nEaxtXR86XZUrE7jHNONd8nGEqK5y8hJ~Z88OdCnzPvzl1rULzPM~~uG3mhaY9Z5a0Os9vMtD5eV~vIizxmNbmaaozvSMBpWUly02nx27wyO3nLiteUpvutnGsdOC67O2vY1eW97zn3WLzO~GE3jnudzqLlbwzvfW0g05fMIa25EtcdtPOJc7qG5wvJPW20pR1SJGdNe9tMec7fE~fG~2=MTdVw3m2D4SfBtTdc3hF8Jb74Zba8y~GW2uGWWG5c7eHvgXPmuG9HLbnTXvg7bkdQnmpfTunNz1B7PL2POE7nxrrlz1hnex45lo4W=VE~WHO3fWvlXXnHDPnHbeuWB9JrbzfXfHbO6WmnWmPfUj3zntpj1Eztpz3Ge6wPgWFTM7PGdY3K2nyLrTrzPDGnzzl2dhqOoQ1orhhZqdNUjNRry28TlHQ6WOnR1XHKzzXcVXOKXtq~lcuYStfF9K8Yb3POdPpmjKWo8uR5XY:1)
