### ISSUE TITLE
经过排序的文件导入后存在数据显示错误

### ISSUE THREAD

**Issue by Lightczx** [voderl/genshin-gacha-analyzer#27]
将经过排序的文件导入后
存在数据显示错误
似乎是因为只能正序读入么？

**Comment by voderl** [comment]
感谢反馈。
目前是默认抽卡记录文件是已经排序过的，在计算数据时也按照已排序过来处理。这样考虑的原因之一，比如十连抽，直接按照时间排序可能会存在顺序错乱的情况。(虽然现在的排序算法按理来说应该是稳定的) 

目前的话，也不建议对抽卡源文件做更改，建议先再导出一个没有经过排序的，或者excel里直接按照总次数或时间对所有数据排序。如果真的有什么强烈需求，我添加一个导入数据后再将所有数据按照时间排序也可以。

**Comment by Lightczx** [comment]
但是仅仅是总体reverse了一下数据就不对劲了
确实是只能导入最新的记录在最下方这样么

**Comment by voderl** [comment]
现在导入文件应该会重新排序，可以试一下。
