### ISSUE TITLE
“合格仓鼠”成就只算了已有记录，未匹配当前时间

### ISSUE THREAD

**Issue by soulgazor** [voderl/genshin-gacha-analyzer#28]
比如本人的抽卡记录，程序判定“从2020/12/24到2021/01/12没有使用「纠缠之缘」进行抽卡，持续时间为19 天17 时”
只看旧数据没问题，但是事实上，从上次抽卡至今（2021/09/05到2021/10/18），我已经43天没抽卡了，
这个可以通过计算最后抽卡时间和当前时间来得出数据的

**Comment by voderl** [comment]
因为抽卡记录没什么更新及时性(尤其是 excel 文件)，很有可能你现在看到的是很久之前的抽卡记录，所以就没有考虑计算到现在的时间。
