### ISSUE TITLE
使用降序排序的xlsx文件时，读取内容与实际不符

### ISSUE THREAD

**Issue by NatralMicsear** [voderl/genshin-gacha-analyzer#29]
导入降序排序的xlsx（新在前旧在后，刻记牛杂店是这么输出的）时，十连的顺序会被反着读取导致问题。
我猜是默认按时间排序，而十连的时间都一样导致的，按祈愿id排序应该可以解决这个问题。

**Comment by voderl** [comment]
感谢反馈，因为不是所有的 excel 文件都有着祈愿 id 这一项的，靠祈愿 id 有点不太行。
现在一个池子里所有记录顺序都是倒序时，会按照降序来处理。
但在降序情况下，如果某个池子只有十连抽，则会判定为正序，考虑到这种情况很少，先这样处理吧

**Comment by Lightczx** [comment]
@Scighost

**Comment by Scighost** [comment]
这个简单
![image](https://user-images.githubusercontent.com/61003590/140514021-aec1ea02-9b55-4418-80b9-ddf7ad02426a.png)
