### ISSUE TITLE
建议增加饼图以及五星历史记录

### ISSUE THREAD

**Issue by sunfkny** [voderl/genshin-gacha-analyzer#3]
其实就是复刻 https://github.com/biuuu/genshin-gacha-export
这样就可以配合 [安卓获取链接](https://github.com/sunfkny/genshin-gacha-export-js/blob/main/README.md#%E5%AE%89%E5%8D%93%E8%8E%B7%E5%8F%96%E9%93%BE%E6%8E%A5) 在安卓端导出&分析
另外现在移动端体验一般，需要开电脑模式，最好能自适应移动端

**Comment by voderl** [comment]
安卓端导出也太强了，我争取今天晚上更新一版

**Comment by voderl** [comment]
先简单支持了一下移动端。在自己手机上的几个浏览器测试了一下，目前勉强能用了。可以先测试一下

**Comment by voderl** [comment]
已更新饼图，饼图的导出图片还没做

**Comment by voderl** [comment]
饼图的导出图片也有了，根据设备横竖屏，导出的图片也分横竖屏
