### ISSUE TITLE
无法识别 UIGF v2.2 Excel 祈愿表结构的物品类型

### ISSUE THREAD

**Issue by monsterxcn** [voderl/genshin-gacha-analyzer#32]
最近我根据 [统一可交换祈愿记录标准 v 2.2](https://github.com/DGP-Studio/Snap.Genshin/wiki/StandardFormat#%E7%A5%88%E6%84%BF%E8%A1%A8%E7%BB%93%E6%9E%84) 制作了一个导出抽卡记录 Excel 表格的工具，依照标准在表头写入了 **物品类型**，但是发现导出后在 https://genshin.voderl.cn 无法统计 3 星物品数量，并且抽取数目展示图中 4 星武器和 4 星角色均显示在一起。

我对比了自己导出的 `.xlsx` 和可正常识别的 `.xlsx`，发现正常识别的 `.xlsx` 表头中写的是 **类别**。我查看了此仓库的代码，觉得可能是此行引起的问题：

https://github.com/voderl/genshin-gacha-analyzer/blob/cb2379b4f4ed8848303930eee26a9f2f793f19f4/src/utils/index.ts#L3

在项目的其他地方也普遍使用“类别”的字眼，于是我将 **物品类型** 修改为 **类别**，可以正常区分四星武器和四星角色，三星物品统计也正常了。

此处，我觉得可以考虑也支持一下 UIGF 标准的表头 **物品类型**？

**Comment by voderl** [comment]
感谢反馈~ 这个增加了兼容处理。 由于开发时的开发水平，excel 的键名耦合已经深入膏肓了，所以就在解析时直接将 "物品类型"给映射到 "类别" 上去了 (笑

**Comment by monsterxcn** [comment]
nice！能用就行，用最少的代码修完 bug 就是成功
