### ISSUE TITLE
成就「雨时偏比晴时多」数值统计问题

### ISSUE THREAD

**Issue by preciousmouse** [voderl/genshin-gacha-analyzer#34]
上例子， 角色五星数量 33 个
![image](https://user-images.githubusercontent.com/19190172/160245352-f346176f-154d-449a-900e-638b755e053f.png)

成就中统计 “小保底歪的概率” 看着有些问题诶~ 
![image](https://user-images.githubusercontent.com/19190172/160245236-63fec808-de46-4c22-8be3-51d1f8aa4b6a.png)

概率实际上应该是 12 / 33
成就结论也应该是 小保底**偏向于抽中**当期Up角色

**Comment by voderl** [comment]
感谢反馈。这个是符合预期的，因为大保底是必定抽中的，因此是不会计算到这个概率里的。
