### ISSUE TITLE
双黄蛋的成就数值有歧义

### ISSUE THREAD

**Issue by zhsitao** [voderl/genshin-gacha-analyzer#4]
双黄蛋成就，数值必定显示为2，而一般的理解是这个成就达成了几次就显示几，显示的是双黄蛋的次数而不是绑定为2。

看了一下代码，双黄蛋会显示2，三黄蛋会显示3，感觉既无太大的必要，又容易导致歧义。

建议可以每个X黄蛋（X>1）都单独显示为一个成就，数值为达成次数；或者只显示双黄蛋成就，如果有3黄或以上，则额外显示”极致的欧皇（暂定名）“，描述为十连最多的出金数。

如果太麻烦，也可以考虑只显示达成成就的首次时间，而不显示多余的2。

**Comment by voderl** [comment]
谢谢~ 已上线， X黄蛋(X>1) 成就右侧显示达成次数，如果X>=3, 成就详情中多出一句话，"你就是极致的欧皇!"
