### ISSUE TITLE
建议小保底不展示在成就

### ISSUE THREAD

**Issue by FeletexGee** [voderl/genshin-gacha-analyzer#41]
![6WMSP}Y`I%3T77LCG03CPN0](https://user-images.githubusercontent.com/69303837/199635900-e4c7a379-2883-4ee1-9398-8cb5f787e1c6.png)
如图，真的很损……我的纳西妲啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊😭

这样真的很不友好，如果user心理承受能力不行估计就开始砸电脑了……

**Comment by voderl** [comment]
这个成就是抽取次数最多的一天，并不会关心是否大小保底。
(可以考虑攒一波，都放到下次大保底把这条记录覆盖下去~

**Comment by FeletexGee** [comment]
判定清楚，但是这个提示语真的很损……

**Comment by voderl** [comment]
那有什么文案可以推荐呢？
如果只是说抽取到 xxx，xxx，感觉比较死板 = =
把开心换掉，换成心潮澎湃、欣然一笑其实也是一样的效果，换成难过感伤又属于对角色和武器的负面评价。
(感觉这种属于偏少见的 case，一般一个大保底就覆盖过去了
(虽然不想说，但可能在某些方面会促进分享欲... (×

**Comment by FeletexGee** [comment]
Interesting issue!挺值得思考的，我觉得可以晚上写写作业想一想，把这个扔todo里面，想好了把这个坑填上……🤔
