### ISSUE TITLE
生成分析图时偶尔会出现文字残缺的现象

### ISSUE THREAD

**Issue by ghost** [voderl/genshin-gacha-analyzer#44]
![charts](https://user-images.githubusercontent.com/119989194/218913307-8d99be55-2cc8-4d71-b747-d42d685a5434.png)

刷新网页后，选择生成图片，部分文字残缺

重复刷新几次后偶尔会生成正常图片

系统：Windows-10-10.0.19045-SP0
浏览器：Microsoft Edge 109.0.1518.70 (正式版本) (64 位)

**Comment by voderl** [comment]
感谢反馈。不过这个问题我这边复现不了，也是第一次见到。感觉像是渲染成 canvas 时出现了问题，不太像是代码的原因。
在你的浏览器里是可以稳定复现的吗？可以把浏览器版本更新下再试试。

**Comment by ghost** [comment]
是的，我尝试了更新浏览器到最新版 Microsoft Edge 版本 110.0.1587.46 (正式版本) (64 位)，然后清除缓存，这个问题依然会出现

导入 UIGF Json 数据，然后选择“导出图片”，第一次导出必定有残缺的文字，后续多次尝试导出，都是正常图片。

刷新页面后，导出图片时依然是第一次会有残缺文字，再次尝试导出正常

**Comment by voderl** [comment]
使用了同样版本的 Edge，同样的路径但并不能复现，都是正常图片。
生成别的图片也会有这个问题吗？比如下面的图片云、成就图

**Comment by ghost** [comment]
只有这个一个图片有问题，其他经过试验都是正常的

**Comment by voderl** [comment]
感谢反馈，不过这个问题我这边复现不了。
可能与个人配置相关，我先 close 掉了，非常抱歉。
