### ISSUE TITLE
新成就的一点想法

### ISSUE THREAD

**Issue by zhsitao** [voderl/genshin-gacha-analyzer#5]
一点关于新成就的不成熟想法：

可选名称：四叶草
大致描述：你总共在xx个十连中，有4个或以上4星或5星。

可选名称：福至五彩
大致描述：你总共在xx个十连中，有5个或以上的4星或5星。

可选名称：这才是角色池！
大致描述：在一次十连中，抽出的角色不少于武器。（即至少有5个角色）

可选名称：拒当保底人，拜拜保底人
大致描述：在常驻池和角色UP池中，有xx次（/yy次总数）在74发（<=73）保底（概率UP）前出金。

可选名称：拒当保底人，拜拜保底人（武器池）
大致描述：在武器池中，有xx次（/yy次总数）在63发（<=62）保底（概率UP）前出金。

注：
角色池74发概率UP来源：https://ngabbs.com/read.php?tid=25461793
武器池63发概率UP来源：https://ngabbs.com/read.php?tid=25678614

**Comment by voderl** [comment]
赞，我觉得这些都可以加上。 不过后两个可以考虑超过一定的比例才显示

**Comment by zhsitao** [comment]
我把总次数放在括号的本意，是取括号里内容可选的含义，也就是可以不显示总次数，只显示欧（不保底）的次数。毕竟自己就是个非酋。。。

**Comment by voderl** [comment]
已更新。目前情况，前两个不会同时展示(满足第二个时不展示第一个)，后两个合并成了一个，没有比例限制。可以去看一下是否符合预期，有问题随时提出

**Comment by voderl** [comment]
看了几个别人生成的成就图。感觉"拒当保底人"的成就有点过长了，而且基本上都会显示。这个成就关注度个人感觉不高，还有概率Up等概念也不太好去解释，考虑暂时删除掉这个成就，抱歉啦

**Comment by zhsitao** [comment]
> 已更新。目前情况，前两个不会同时展示(满足第二个时不展示第一个)，后两个合并成了一个，没有比例限制。可以去看一下是否符合预期，有问题随时提出

挺好的。

不过我本意是这两个成就互不影响的，如果都有就都显示，毕竟会显示成就的达成次数。

我不太清楚两者的概率，但是都显示可能可以让欧的人或氪老看着更舒服一点？就是如果我达成1个福至五彩，我可能有7、8次四叶草了，显示8次四叶草也并不输于1次福至五彩。

**Comment by zhsitao** [comment]
> 看了几个别人生成的成就图。感觉"拒当保底人"的成就有点过长了，而且基本上都会显示。这个成就关注度个人感觉不高，还有概率Up等概念也不太好去解释，考虑暂时删除掉这个成就，抱歉啦

没事，本来就是一个想法，如果觉得不合适就删掉。不过如果判断条件是达成次数大于0的话，那确实都会显示。。

角色池和常驻池的期望是大约35%~36%的概率不吃软保底，武器池不太确定不过应该差不太多，如果想突出欧的话，也可以像你最开始提出的那样，设置成40%或一半以上才显示？

另外，成就名称我的本意是”拒当保底人，拜拜保底人“中二选一，或者是其它更恰当的名字，都显示确实过长了。。描述的话，也可以考虑不写出”XX抽概率UP“这几个字，改为”软保底“？不太确定好不好，也可能更差了。。。

**Comment by zhsitao** [comment]
如果还是觉得概率UP太复杂的话，或许还有一种方式，就是类似已有的「单抽出奇迹!」成就，不过只计算10连抽或者全部计算，描述大概为”在20/30/40发内，（通过10连抽）获取5星角色或武器“。

具体是只计算10连抽还是全部都包括，20、30还是40发我也不太确定哪个效果更好。概率上对于角色池和常驻池，大概20发是11.34%，30发是16.52%，40发是21.39%；武器池比这个概率略大但我没有详细数据。另外，10连抽和单抽的每发概率应该是相同的。

我当时提出这个成就的另一个想法是，这些成就里，并没有可以展示基本只抽10连抽而不太吃保底的情况。「欧皇时刻」只展示了一次，而「单抽出奇迹!」又仅限单抽。。

**Comment by voderl** [comment]
> > 已更新。目前情况，前两个不会同时展示(满足第二个时不展示第一个)，后两个合并成了一个，没有比例限制。可以去看一下是否符合预期，有问题随时提出
> 
> 挺好的。
> 
> 不过我本意是这两个成就互不影响的，如果都有就都显示，毕竟会显示成就的达成次数。
> 
> 我不太清楚两者的概率，但是都显示可能可以让欧的人或氪老看着更舒服一点？就是如果我达成1个福至五彩，我可能有7、8次四叶草了，显示8次四叶草也并不输于1次福至五彩。

两个不会同时展示，主要是为了限制成就数目。毕竟是希望把成就分享出去的，而图片过长会让人不想去看，所以同质的成就还是建议只显示最高的那个。情有独钟成就其实也想合并一下，但考虑到可能有多个角色获取数目相同，所以就还没去改。

> 如果还是觉得概率UP太复杂的话，或许还有一种方式，就是类似已有的「单抽出奇迹!」成就，不过只计算10连抽或者全部计算，描述大概为”在20/30/40发内，（通过10连抽）获取5星角色或武器“。
> 
> 具体是只计算10连抽还是全部都包括，20、30还是40发我也不太确定哪个效果更好。概率上对于角色池和常驻池，大概20发是11.34%，30发是16.52%，40发是21.39%；武器池比这个概率略大但我没有详细数据。另外，10连抽和单抽的每发概率应该是相同的。
> 
> 我当时提出这个成就的另一个想法是，这些成就里，并没有可以展示基本只抽10连抽而不太吃保底的情况。「欧皇时刻」只展示了一次，而「单抽出奇迹!」又仅限单抽。。

之前最开始就有一个成就是叫 单抽出奇迹？，描述为：单抽获取五星的数目为xx，十连获取五星的数目为yy， 然后改成了现在的"单抽出奇迹! "，或许可以把名字再改回去，描述改为：在xx抽内，通过单抽获取五星数目为yy，十连获取五星数目为zz ？

其实单抽出奇迹目前30抽限制也挺想改的，但因为武器池概率偏大一点，所以感觉还是(30/40/50)好一点吧 (×

**Comment by zhsitao** [comment]
> 之前最开始就有一个成就是叫 单抽出奇迹？，描述为：单抽获取五星的数目为xx，十连获取五星的数目为yy， 然后改成了现在的"单抽出奇迹! "，或许可以把名字再改回去，描述改为：在xx抽内，通过单抽获取五星数目为yy，十连获取五星数目为zz ？
> 
> 其实单抽出奇迹目前30抽限制也挺想改的，但因为武器池概率偏大一点，所以感觉还是(30/40/50)好一点吧 (×

你说的这个”在xx抽内，通过单抽获取五星数目为yy，十连获取五星数目为zz ？“听起来不错啊。

抽数的话，如果觉得30抽太少，我个人感觉也许40抽好点？本身是20%~25%的概率，而直观感觉上，40抽之前出对于保底70、80抽来说也绝对是欧了，又不至于50抽感觉和武器软保底63抽没太大区别。

**Comment by voderl** [comment]
这个修改纠结了好久(×
因为可能有人在40抽水位前就只单抽了一次，然后出金了。其实他可能100次十连，出了好几个金。这种情况下更应该展示 单抽出奇迹 的。
然后又尝试加上了出金率，在40抽水位前的(单抽出金/总单抽数)。这比例的概念比较奇怪，可能给人误导，还是决定删掉。

目前是仅仅看40抽水位前，单抽和十连的出金数，来决定是否出奇迹
(加水位的目的主要也是防止有人看到要保底就单抽了，这种就和出奇迹不符了)

**Comment by zhsitao** [comment]
> 这个修改纠结了好久(×
> 因为可能有人在40抽水位前就只单抽了一次，然后出金了。其实他可能100次十连，出了好几个金。这种情况下更应该展示 单抽出奇迹 的。
> 然后又尝试加上了出金率，在40抽水位前的(单抽出金/总单抽数)。这比例的概念比较奇怪，可能给人误导，还是决定删掉。
> 
> 目前是仅仅看40抽水位前，单抽和十连的出金数，来决定是否出奇迹
> (加水位的目的主要也是防止有人看到要保底就单抽了，这种就和出奇迹不符了)

看了一下最新的修改，感觉不错。描述提个小建议，也许可以考虑改为“在抽卡不超过40抽时共获取xx个五星，其中……”？
