### ISSUE TITLE
这个统计系统好像出了点问题

### ISSUE THREAD

**Issue by jacketname** [voderl/genshin-gacha-analyzer#6]
![bugReportGacha](https://user-images.githubusercontent.com/80352681/110515267-0f5f2500-80bd-11eb-87cb-7fc10a6e3943.png)

我只有一命刻晴，一个天空之傲，可以看出这些重复的时间是一样的

**Comment by voderl** [comment]
如果这个有问题，那其他的数据应该也有问题。但我这边复现不出来，能分享一下xlsx文件吗？

**Comment by jacketname** [comment]
“如果这个有问题，那其他的数据应该也有问题。但我这边复现不出来，能分享一下xlsx文件”

很抱歉，似乎是我的导出软件出了问题，打扰了。
