### ISSUE TITLE
图片下载不了

### ISSUE THREAD

**Issue by yukiryo** [voderl/genshin-gacha-analyzer#7]
![Screenshot_20210313-110522](https://user-images.githubusercontent.com/58250223/111017018-08e9e980-83ec-11eb-9a70-b6d2c442c12b.jpg)

**Comment by voderl** [comment]
感谢反馈，你这是哪个浏览器？暂时可以先换一个浏览器重试。
下载是用的FileSaver库，可能部分浏览器兼容性不行。我测试一下看看有没有解决方法= =

**Comment by yukiryo** [comment]
> 感谢反馈，你这是哪个浏览器？暂时可以先换一个浏览器重试。
> 下载是用的FileSaver库，可能部分浏览器兼容性不行。我测试一下看看有没有解决方法= =

用的via，换chrome好了
