### ISSUE TITLE
希望能统计溢出角色

### ISSUE THREAD

**Issue by tldzyx** [voderl/genshin-gacha-analyzer#9]
就是重复角色超过7个的部分(本体1+命座6), 希望能统计出来分别溢出多少个, 米忽悠还我血汗钱, 5个星辉算啥事

**Comment by voderl** [comment]
如果统计溢出的角色获得多少星辉，那就真的杀人诛心了hh。
这个的话，部分角色因为赠送可能统计结果不太对，如果只是图一乐的话确实可以加上。感谢建议，有好一点的成就标题提供嘛

**Comment by tldzyx** [comment]
> 如果统计溢出的角色获得多少星辉，那就真的杀人诛心了hh。
> 这个的话，部分角色因为赠送可能统计结果不太对，如果只是图一乐的话确实可以加上。感谢建议，有好一点的成就标题提供嘛

"爷不差钱"/"为我所爱" 等等可以算成就吧, 一般溢出都是为了抽别的角色造成的.

**Comment by voderl** [comment]
想了一下，感觉这个成就如果看到的话就只有负面效果了。平民溢出四星心疼，氪佬溢出五星更心疼。
在想有没有必要开一个新版块，展示一些统计数据，有点苦恼。

**Comment by tldzyx** [comment]
> 想了一下，感觉这个成就如果看到的话就只有负面效果了。平民溢出四星心疼，氪佬溢出五星更心疼。
> 在想有没有必要开一个新版块，展示一些统计数据，有点苦恼。

个人倒是对成就没所谓, 就是想看统计结果, 也许可以提供这么个统计功能, 可能造成心理不适的默认不显示, 用户可以自行选择是否显示出来.

**Comment by voderl** [comment]
目前更新了一个文字云，在分析图那一栏，虽然有点丑，但是可以展示获取的每个角色的数目。溢出统计还在考虑
